"""empty message

Revision ID: 152de5f8e2a2
Revises: 
Create Date: 2025-03-11 10:21:35.942279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '152de5f8e2a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('runescape_name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('progression_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('stat_category', sa.String(), nullable=True),
    sa.Column('stat_value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard')
    op.drop_table('announcements')
    op.drop_table('users')
    # ### end Alembic commands ###
